### PR TITLE
Fix for Foundry USA Pool

### PR DESCRIPTION
**Pull request by zowki**
Fix for this block:
https://btc.com/btc/block/695930

### CODE REVIEW

**Comment by dubuqingfeng** [comment]
and you can set coinbase address.

**Comment by dubuqingfeng** [comment]
@liuyangovo 看一下

**Comment by Sparky1ers** [comment]
Ok here is my coinbase wallet address

qqssdsycr56r9lf5ttajxtp3eshk52ugxqg5pcfxzu

**Comment by Sparky1ers** [comment]
Coinbase BCH wallet address

qqssdsycr56r9lf5ttajxtp3eshk52ugxqg5pcfxzu

**Comment by lowkeyxavier** [comment]
@satoshi is back

**Pull request merged**
