### PR TITLE
Add sbicrypto pool

### PR DESCRIPTION
**Pull request by blocksmither**
Adding different variations of sbicrypto block signing.

### CODE REVIEW

**Review by paaqp — APPROVED** [review]

**Comment by blocksmither** [comment]
@paaqp @liuyangovo @dubuqingfeng 
Please check. Thank you.

Fixed:
Merge conflict
String pattern

**Comment by blocksmither** [comment]
Logos at 
https://github.com/sbicrypto/presskit/tree/main/logos/Pool%20and%20Product%20Logos

**Comment by dubuqingfeng** [comment]
Logos at https://github.com/sbicrypto/presskit/tree/main/logos/Pool%20and%20Product%20Logos

404

**Comment by blocksmither** [comment]
> Logos at https://github.com/sbicrypto/presskit/tree/main/logos/Pool%20and%20Product%20Logos
> 
> 404

@dubuqingfeng  Try again. Fixed.

**Pull request closed without merging**
