### PR TITLE
Update pools.json

### PR DESCRIPTION
**Pull request by cedriccalery**

### CODE REVIEW

**Comment by cedriccalery** [comment]
@dubuqingfeng how to change the display logo for pool on btc.com? thanks.

**Comment by dubuqingfeng** [comment]
you can upload an icon. 
16*16 png.
We will process after received.
or you can pm me.
wechat: dubuqingfeng.

**Comment by dubuqingfeng** [comment]
and You can provide a real-time hashrate API.

**Comment by cedriccalery** [comment]
lubian16

Here's the 16x16 icon file. Thanks!

**Pull request merged**
