### PR TITLE
Correct MaraPool URL and Payout Address

### PR DESCRIPTION
**Pull request by liceaga**
This PR reflects the new MaraPool website and correct payout address.

### CODE REVIEW

**Comment by liceaga** [comment]
@liuyangovo 请查阅

**Comment by Sparky1ers** [comment]
Yes this is my correct pay out address lifeinthe509@gmail.com thank you kindly so much.

**Comment by Sparky1ers** [comment]
Pay out address for Json is also mine you can send payment to lifeinthe509@gmail.com

**Comment by Sparky1ers** [comment]
Thank you for your email and your help are you keeping half of the money
you can I said I would give half to you for helping me retrieve the money.

**Comment by Sparky1ers** [comment]
Bitcoin cash BCH right 6.2500000

**Pull request merged**
